name = "drivesight-website"
compatibility_date = "2024-01-01"

[assets]
directory = "."

[build]
command = ""
# wrangler.toml
name = 'noisy-disk-8a54ai-mentions-tracker'
{
  "observability": {
    "enabled": false,
    "head_sampling_rate": 1,
    "logs": {
      "enabled": true,
      "head_sampling_rate": 1,
      "persist": true,
      "invocation_logs": true
    },
    "traces": {
      "enabled": false,
      "persist": true,
      "head_sampling_rate": 1
    }
  }
}
